layout_spectrum: 0.3847118
typography_spectrum: 0.3383459
color:
  saturation: 0.4141604
  lightness: 0.5745614
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: AVESSAS
